### PR TITLE
Parsing fixes

### LINKED ISSUE #7: Dots in attribute names
To my knowledge having dots in attribute names is valid, but it doesn't seem to match `xeno`'s expectations.

```haskell
> import qualified Xeno.DOM                                                                                                   
> :set -XOverloadedStrings                                                                                           
> Xeno.DOM.parse "<foo bar.baz=\"qux\"></foo>"                                                                       
Left (XenoParseError "Expected =, got: . at character index: 8")
```

### PR DESCRIPTION
**Pull request by qrilka**
Fixes #7 #6 
While debugging fixes for root node behind spases I was seeing quite suspicious numbers in "DOM indexes" array `r` so I think it needs some extra tests and maybe some fixes

### CODE REVIEW

**Comment by qrilka** [comment]
@ocramz any news on this one?

**Comment by chrisdone** [comment]
This is cool, thanks. I'll let @ocramz be the judge. In the spirit of xeno's performance golfing, this is the diff of the benchmarks before and after:

https://gist.github.com/chrisdone/461199db82d06707e0d2ae16bc8cb5ab/revisions

This makes xeno allocate 8x more memory and adds 10%~ extra time. It's possible that this is an inevitable result of fixing things, but there *may* be something you can shave off.

**Comment by qrilka** [comment]
Oh, thanks @chrisdone for your feedback, I'll take a look into that higher memory consumption - it looks suspicious.
I plan to use `xeno` for fast "unsafe" parsing in `xlsx` library and without these fixes it just doesn't work

**Comment by qrilka** [comment]
@chrisdone it appears that `INLINE` on `parseName` which just checked 1st symbol resulted in those extra allocations, removing it brings them back to previous levels - https://gist.github.com/qrilka/71843bc4fb8643b1aa341bcec3f9bc17/revisions

**Comment by chrisdone** [comment]
@qrilka Looks good to me!

**Comment by qrilka** [comment]
@ocramz did you have time to look into it?

**Comment by ocramz** [comment]
Sorry @qrilka for the delay; thanks for your contribution!

**Comment by qrilka** [comment]
thanks @ocramz 
Could I hope for a new `package release on Hackage soon? I'd like to add it as a dependency to `xlsx`

**Comment by ocramz** [comment]
Yep, the latest version with your additions is up now! http://hackage.haskell.org/package/xeno-0.3 : )

**Comment by qrilka** [comment]
@ocramz sorry for repeating myself but changelog for 0.3 on Hackage doesn't say anything about the version 0.3 it refers too...

**Comment by ocramz** [comment]
Ooops, I always forget to update changelogs

**Comment by ocramz** [comment]
@qrilka could you help me here perhaps? how to summarise your addition?

**Comment by qrilka** [comment]
Sure, it's mainly 2 things:
* fixing name parsing (for attributes and tags) so it conforms with the XML spec
* fixing parsing failure when root tag is preceded by  white space (though without checking for white space characters specifically)

**Comment by ocramz** [comment]
Thanks @qrilka , I've updated the changelog in http://hackage.haskell.org/package/xeno-0.3.1

**Pull request merged**
