### PR TITLE
Use github actions instead of travis

### PR DESCRIPTION
**Pull request by jappeace**
Because travis dropped it's free support for opensource software,
this PR moves this library to github actions which is still free.

### CODE REVIEW

**Comment by jappeace** [comment]
should fix this: https://github.com/ocramz/xeno/issues/52

**Comment by jappeace** [comment]
@pkamenarsky could you review this?

**Comment by pkamenarsky** [comment]
Thanks for the PR! Shouldn't we also update the badge in the `README`?

**Comment by jappeace** [comment]
I updated the badge.

I just realized however that github actions still need to be enabled for this to work.

**Comment by pkamenarsky** [comment]
@ocramz could you enable github actions?

**Comment by qrilka** [comment]
Didn't @mgajda take over the project? Probably he has permissions to do that or maybe @dmalkr

**Review by ocramz — APPROVED** [review]
LGTM !

**Comment by ocramz** [comment]
Apologies @jappeace @pkamenarsky for being unresponsive.

**Pull request merged**
